In [2]:
class MulLayer:
    def __init__(self):
        self.x = None
        self.x = None
    
    def forward(self,x,y):
        self.x = x 
        self.y = y
        out = x * y        

        return out
    
    def backward(self, dout):
        dx = dout * self.y 
        dy = dout * self.x
        
        return dx, dy
        

apple = 100
apple_num = 2 
tax = 1.1

mul_apple_layer = MulLayer()
mul_tax_layer = MulLayer()

apple_price = mul_apple_layer.forward(apple, apple_num)
price = mul_tax_layer.forward(apple_price, tax)

print(price)

220.00000000000003


In [4]:
dprice = 1 
dapple_price , dtax = mul_tax_layer.backward(dprice)
dapple, dapple_num = mul_apple_layer.backward(dapple_price)

print(dapple, dapple_num, dtax)

2.2 110.00000000000001 200


In [7]:
class AddLayer:
    def __init__(self):
        pass
    
    def forward(self, x, y):
        out = x + y
        
        return  out
    
    def backward(self, dout):
        dx = dout*1 
        dy = dout*1
        
        return dx, dy


In [10]:
apple_num = 2 
apple_price = 100
orange_num = 3
orange_price = 150
tax = 1.1

mul_apple_price = MulLayer()
mul_orange_price = MulLayer()
add_orange_apple = AddLayer()
mul_orange_apple_tax = MulLayer()

apple_price = mul_apple_price.forward(apple_price, apple_num)
orange_price = mul_orange_price.forward(orange_price, orange_num)
orange_apple = add_orange_apple.forward(apple_price, orange_price)
orange_apple_tax = mul_orange_apple_tax.forward(orange_apple,tax)
price = orange_apple_tax

dprice = 1

dorange_apple, dtax = mul_orange_apple_tax.backward(dprice)
dapple_price, dorange_price = add_orange_apple.backward(dorange_apple)
dapple, dapple_num = mul_apple_price.backward(dapple_price)
dorange, dorange_num = mul_orange_price.backward(dorange_price)


In [11]:
print(price)
print(dapple_num, dapple,dorange, dorange_num, dtax)

715.0000000000001
110.00000000000001 2.2 3.3000000000000003 165.0 650


In [12]:
class Relu:
    def __init__(self):
        self.mask = None
        
    def forward(self, x):
        self.mask = (x <= 0)
        out = x.copy()
        out[self.mask] = 0
        
        return out
    
    def backward(self, dout):
        dout[self.mask] = 0
        dx = dout
        
        return dx

In [17]:
import numpy as np
x = np.array([[1.0,-0.5],[-2.0, 3.0]])
print(x)

mask = (x <= 0)
print(mask)

x[mask] = 0
print(x)

[[ 1.  -0.5]
 [-2.   3. ]]
[[False  True]
 [ True False]]
[[1. 0.]
 [0. 3.]]


In [18]:
class Sigmoid:
    def __init__(self):
        self.out = None
        
    def forward(self, x):
        out = 1 / (1 + np.exp(-x))
        self.out = out 
        
        return out
    
    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out
        
        return dx 

In [21]:
X = np.random.rand(2)
W = np.random.rand(2,3)
B = np.random.rand(3)

print(X.shape)
print(W.shape)
print(B.shape)

Y = np.dot(X, W) + B 
print(Y.shape)

(2,)
(2, 3)
(3,)
(3,)


In [22]:
X_dot_W = np.array([[0,0,0],[10,10,10]])
B = np.array([1,2,3])

print(X_dot_W)
print(X_dot_W + B)

[[ 0  0  0]
 [10 10 10]]
[[ 1  2  3]
 [11 12 13]]


In [23]:
dY = np.array([[1,2,3],[4,5,6]])
print(dY)

dB = np.sum(dY, axis = 0)
print(dB)


[[1 2 3]
 [4 5 6]]
[5 7 9]


In [25]:
class Affine:
    def __init__(self, W, b):
        self.W = W 
        self.b = b 
        self.x = None
        self.dW = None
        self.db = None
        
    def forward(self, x):
        self.x = x 
        out = np.dot(x, self.W) + self.b
        
        return out
    
    def backward(self, dout):
        dx = np.dot(dout, self.W.T)
        self.dW = np.dot(self.x.T, dout)
        self.db = np.sum(dout, axis = 0)
        
        return dx
        
        

In [24]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [38]:
import sys, os
sys.path.append(os.pardir)
import numpy as np

from common.layers import * 
from common.gradient import numerical_gradient
from collections import OrderedDict

class TwoLayerNet:
    
    def __init__(self, input_size, hidden_size, output_size, weight_init_std =0.01):
        
        self.params = {}
        self.params['W1'] = weight_init_std *  np.random.randn(input_size, hidden_size)
        self.params['b1'] = np.zeros(hidden_size)
        self.params['W2'] = weight_init_std *  np.random.randn(hidden_size, output_size)
        self.params['b2'] = np.zeros(output_size)
        
        self.layers = OrderdDict()
        self.layers['Affine1'] = Affine(self.params['W1'], self.params['b1'])
        self.layers['Relu1'] = Relu()
        self.layers['Affine2'] = Affine(self.params['W2'], self.params['b2'])
        self.listLayer = SoftmaxWithLoss()
        
def predict(self, x):
    for layer in self.layers.values():
        x = layer.forward(x)   
        
    return x 