In [29]:
import numpy as np 

In [1]:
# 곱샘계층 
class MulLayer:
    def __init__(self):
        self.x = None
        self.y = None
    def forward(self, x, y):
        self.x = x
        self.y = y
        out = x * y

        return out
    
    def backward(self, dout):
        dx = dout * self.y 
        dy = dout * self.x
        
        return dx, dy

In [2]:
apple = 100 
apple_num = 2 
tax = 1.1

mul_apple_layer = MulLayer()
mul_tax_layer = MulLayer()

apple_price = mul_apple_layer.forward(apple,apple_num)
price = mul_tax_layer.forward(apple_price, tax)

print(price)

220.00000000000003


In [3]:
dprice = 1
dapple_price, dtax = mul_tax_layer.backward(dprice)
dapple, dapple_num = mul_apple_layer.backward(dapple_price)

print(dapple_price, dtax, dapple, dapple_num)

1.1 200 2.2 110.00000000000001


In [4]:
class AddLayer:
    def __init__(self):
        pass
    def forward(self, x, y):
        out = x+y
        return out
    def backward(self, dout):
        dx = dout * 1
        dy = dout * 1

        return dx, dy

In [21]:
apple, apple_num = 100, 2
orange, orange_num = 150,3
tax = 1.1
mul_apple_layer = MulLayer()
mul_orange_layer = MulLayer()
add_apple_orange_layer = AddLayer()
mul_tax_layer = MulLayer()

In [24]:
#순전파
apple_price = mul_apple_layer.forward(apple, apple_num)
orange_price = mul_orange_layer.forward(orange, orange_num)
all_price = add_apple_orange_layer.forward(apple_price, orange_price)
price = mul_tax_layer.forward(all_price, tax)

print(price)

715.0000000000001


In [23]:
#역전파
dprice = 1 
dall_price, dtax = mul_tax_layer.backward(dprice)
dapple_price, dorange_price = add_apple_orange_layer.backward(dall_price)
dapple, dapple_num = mul_apple_layer.backward(dapple_price)
dorange, dorange_num = mul_orange_layer.backward(dorange_price)

print(dapple, dapple_num )
print(dorange, dorange_num )

2.2 110.00000000000001
3.3000000000000003 165.0


In [25]:
class Relu:
    def __init__(self):
        self.mask = None
    def forward(self, x):
        self.mask = (x<=0)
        out = x.copy()
        out[self.mask] = 0

        return out

    def backward(self, dout):
        dout[self.mask] = 0
        dx = dout

        return dx

In [26]:
c = Relu()

In [30]:
c.forward(np.array([-1]))

array([0])

In [35]:
np.array([-1,1,0,-2]) <=0 

array([ True, False,  True,  True])

In [34]:
out = np.array([-1,1,0,-2])

In [37]:
out[np.array([-1,1,0,-2]) <=0 ] = 0
out

array([0, 1, 0, 0])