In [1]:
import numpy as np 

In [2]:
x = np.arange(1,4)

In [4]:
x.__class__

numpy.ndarray

In [6]:
x.shape

(3,)

In [7]:
W = np.array([[1,2,3],[4,5,6]])
print(W.shape)
print(W.ndim)

(2, 3)
2


In [9]:
W = np.array([[1,2,3,],[5,6,7]])
X = np.array([[0,1,2,],[3,4,5]])
print(W + X) 
print(W * X)

[[ 1  3  5]
 [ 8 10 12]]
[[ 0  2  6]
 [15 24 35]]


In [11]:
A = np.array([[1,2],[3,4]])
A * 10 

array([[10, 20],
       [30, 40]])

In [12]:
A = np.array([[1,2],[3,4]])
b = np.array([10,20])
A * b 

array([[10, 40],
       [30, 80]])

In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

32

In [14]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6,],[7,8]])
np.matmul(A,B)

array([[19, 22],
       [43, 50]])

In [15]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [24]:
import numpy as np 

def sigmoid(x):
    return 1/ (1+np.exp(-x))

x = np.random.randn(10,2)
W1 = np.random.randn(2,4)
b1 = np.random.randn(4)
W2 = np.random.randn(4,3)
b2 = np.random.randn(3)

h = np.matmul(x,W1) + b1
a = sigmoid(h)
s = np.matmul(a,W2) + b2


In [25]:
s

array([[ 0.95870585, -2.93282237, -0.50114159],
       [ 0.91480445, -2.98253661, -0.58259132],
       [ 1.57090847, -2.05346202,  0.02619953],
       [ 0.29599079, -3.71637342, -0.71753664],
       [ 0.66233553, -3.31757169, -0.20478374],
       [ 0.36055027, -3.5537131 , -0.95795431],
       [ 0.6337569 , -3.32594777, -0.57128964],
       [ 0.44545963, -3.5124983 , -0.85880127],
       [ 0.46450822, -3.47799851, -0.91157613],
       [ 0.183758  , -3.85683164, -0.75495444]])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])